### ISSUE TITLE
Add opportunity to style countries container

### ISSUE THREAD

**Issue by RomanHavdo** [LacunaSoftware/lac-mat-tel-input#4]
Hi,

I would like to change height of dropdown container. I can change it only by using ng-deep and map-panel, but it will affect my global styles. Could you please approve my [PR](https://github.com/LacunaSoftware/lac-mat-tel-input/pull/3) , that I can use this unique class name for styling.

**Comment by andreflourenco** [comment]
Hi @RomanHavdo your PR was merged, thank you very much.
